AWSTemplateFormatVersion: '2010-09-09'
Description: 'Creating S3 Bucket'

Parameters:
  availabilityZone:
    Description: 'AZ for instance'
    Type: AWS::EC2::AvailabilityZone::Name
  ec2IamStackName: 
    Description: 'IAM stack name for IAM role'
    Type: String
  imageId:
    Description: 'AMI id'
    Type: AWS::EC2::Image::Id
  instanceType:
    Description: 'Instance Type'
    Type: String
  keyName:
    Description: 'Key Pair Name'
    Type: String
  ec2NetworkSecurityStackName:
    Description: 'Network Security Stack name'
    Type: String
  userData:
    Description: 'UserData for the instance in base64 format'
    Type: String
  subnetId:
    Description: 'subnet ID for particular AZ'
    Type: CommaDelimitedList
  indexNumber:
    Description: 'Get Index number for SubnetID and AZ. This should match'
    Type: Number

Resources: 
  ec2Instance:
    Type: AWS::EC2::Instance
    Properties: 
      AvailabilityZone: 
        Fn::Select:
          - !Ref indexNumber
          - !Ref availabilityZone
      IamInstanceProfile: 
        Fn::ImportValue: !Sub "${ec2IamStackName}-roleName"
      ImageId: !Ref imageId
      InstanceType: !Ref instanceType
      KeyName: !Ref keyName
      SecurityGroups: 
        - Fn::ImportValue: !Sub "${ec2NetworkSecurityStackName}-securityGroup"
      SubnetId: 
        Fn::Select: 
          - !Ref indexNumber 
          - !Ref subnetId
      UserData: !Ref userData
      Volumes:
        - 
          VolumeId: !Ref ec2Volume
          Device: '/dev/sdh'

  ec2Volume:
    Type: AWS::EC2::Volume
    Properties:
      Size: 100
      AvailabilityZone:
        Fn::Select:
          - !Ref indexNumber
          - !Ref availabilityZone

Outputs:

  instanceId:
    Value: !Ref ec2Instance
    Description: 'AWS EC2 instance Id'
    Export:
      Name: !Sub "${AWS::StackName}-ec2InstanceId"
  ec2InstanceAZ:
    Value: !GetAtt ec2Instance.AvailabilityZone
    Description: 'AWS EC2 instance AZ'
    Export:
      Name: !Sub "${AWS::StackName}-ec2InstanceAZ"
  ec2InstancePrivateIp:
    Value: !GetAtt ec2Instance.PrivateIp
    Description: 'Ec2 Instance Private IP'
    Export:
      Name: !Sub "${AWS::StackName}-ec2InstancePrivateIp"
  ec2InstancePublicIp:
    Value: !GetAtt ec2Instance.PublicIp
    Description: 'Ec2 Instance Public IP'
    Export:
      Name: !Sub "${AWS::StackName}-ec2InstancePublicIp"

